package lakeorm

import (
	"context"

	"github.com/datalake-go/lake-orm/backends"
	"github.com/datalake-go/lake-orm/structs"
	"github.com/datalake-go/lake-orm/types"
)

// ExecutionPlan is the opaque artifact a Dialect hands to a Driver. The
// Driver executes the plan without knowing the Dialect's name. Internally
// it is a tagged union of variants (DirectIngest, ParquetIngest,
// ParquetMerge, SQL, Stream, DDL); Dialect constructs them, Driver
// reads the Kind and dispatches.
//
// The type is intentionally a struct (not an interface) so the wire
// shape can evolve without breaking v1+ drivers that consume plans
// they didn't construct.
type ExecutionPlan struct {
	Kind PlanKind
	SQL  string // For KindSQL / KindStream / KindDDL
	Args []any  // SQL-parameter bindings
	// IngestID is the per-operation UUIDv7. Every write plan carries
	// it. The driver stamps it onto every row (direct-ingest) or
	// onto the parquet staging output (parquet-ingest) so the
	// system-managed _ingest_id column is populated on every row.
	// Also the filter predicate on KindParquetMerge's MERGE source.
	IngestID string
	Target   string         // table name for writes
	Staging  StagingRef     // populated for KindParquetIngest
	Rows     any            // typed slice for KindDirectIngest
	Schema   *structs.LakeSchema    // referenced by the Driver for type-aware ingest
	Options  map[string]any // Dialect-specific hints opaque to the Driver
}

// PlanKind identifies the plan variant. Values are stable — drivers
// branch on them.
type PlanKind int

const (
	KindSQL PlanKind = iota
	KindStream
	KindDDL
	KindDirectIngest
	KindParquetIngest
	// KindParquetMerge is the upsert variant of KindParquetIngest.
	// Emitted when the schema carries at least one mergeKey field.
	// Drivers execute MERGE INTO <target> USING (SELECT * FROM
	// <staging> WHERE _ingest_id = '<plan.IngestID>') AS source ON
	// target.<mergeKey> = source.<mergeKey> WHEN MATCHED THEN
	// UPDATE SET * WHEN NOT MATCHED THEN INSERT *. The _ingest_id
	// filter on source bounds the merge to this batch so the
	// operation is O(batch_size) and retry-on-OCC-conflict is
	// idempotent.
	KindParquetMerge
)

// StagingRef names the URI prefix and parts produced by a fast-path
// partition writer. The Driver reads this to emit the
// `INSERT ... SELECT FROM parquet.<prefix>/*.parquet` statement.
type StagingRef struct {
	Backend  backends.Backend
	Prefix   string
	PartKeys []string
	Location types.Location
}

// WriteRequest is what the Client hands the Dialect on Insert.
type WriteRequest struct {
	Ctx    context.Context
	Schema *structs.LakeSchema
	// IngestID is a UUIDv7 correlation ID generated by Client.Insert
	// for every operation. Threads through staging prefix, logs, and
	// the Finalizer's cleanup target. Required for the fast path;
	// Dialect implementations use this (not Idempotency) to compute
	// staging locations.
	IngestID       string
	Records        any
	RecordCount    int
	ApproxRowBytes int
	// Idempotency is an optional caller-supplied deduplication token.
	// Distinct from IngestID: IngestID is internal operational
	// correlation; Idempotency is the contract with the caller for
	// retry safety. Empty when the caller didn't supply one.
	Idempotency   string
	Backend       backends.Backend
	FastPathBytes int            // advisory crossover threshold
	ForcePath     WritePath      // None / ViaGRPC / ViaObjectStorage
	Options       map[string]any // dialect-specific overrides
}

// WritePath is the caller's optional override of the Dialect's routing.
type WritePath int

const (
	WritePathAuto WritePath = iota
	WritePathGRPC
	WritePathObjectStorage
)
